### ISSUE TITLE
How to make full use of WebFace260M dataset?

### ISSUE THREAD

**Issue by Huangzhw0221** [CVExplorer/Face2Exp#2]
Hello, Thanks for your work.
After reading your code, I have two questions. How does the model make use of FR data in the WebFace260M dataset and why the dataset return (image,label) set for both labeled and unlabeled set?
As your code in data.py, for RAFDB dataset, you consider part of data in RAFDB and AFFECTNET (raf_aff_train.csv) as unlabeled data, and for AffectNet dataset, you split it into two sets: labeled_10_balance.csv and training.csv. However, as written in the paper, you may use WebFace260M dataset as FR(unlabeled) data. Do you have any solution to solve it?

**Comment by Huangzhw0221** [comment]
The author has answered this question for me via email, and thanks again for the work of the author.

**Comment by sunggukcha** [comment]
Can you share how to use of WebFace data?
I cannot find a way to use FR data.
Is replacing the unlabeled set to the FR set enough?

**Comment by CZP-1** [comment]
> The author has answered this question for me via email, and thanks again for the work of the author.

Hello, could you send me an email with the author's response? My email address is 2402242823@qq.com.
